name: james-media-keyframes
description: Media Catalog keyframe extraction pipeline
tags:
namespace: default
kubernetes_cluster_vrn: vast:dataengine:kubernetes-clusters:var201-k8s
manifest:
  triggers:
    - name: james-media-catalog-1
      vrn: vast:dataengine:triggers:james-media-catalog
  function_deployments:
    - name: james-keyframe-extractor-1
      function_vrn: vast:dataengine:functions:james-keyframe-extractor
      revision: 1
      config:
        log_level: DEBUG
      resources:
        min_concurrency: 1
        max_concurrency: 10
        autoscaling_rps_factor: 2
        autoscaling_concurrency_overload_factor: "1"
        min_cpu: 200m
        max_cpu: "1"
        min_memory: 256Mi
        max_memory: 1Gi
        timeout: 180
  links:
    - source:
        - james-media-catalog-1
      destination:
        - james-keyframe-extractor-1
      topic: vast:dataengine:topics:engine-broker/main
      config:
        retries: 3
        events_order: unordered
