connector.name=vast
vast.endpoint=${ENV:VAST_ENDPOINT}
vast.access-key-id=${ENV:VAST_ACCESS_KEY}
vast.secret-access-key=${ENV:VAST_SECRET_KEY}
vast.data-endpoints=${ENV:VAST_ENDPOINT}
vast.region=us-east-1
