[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:trino]
command=/usr/lib/trino/bin/launcher run
directory=/usr/lib/trino
autostart=true
autorestart=true
stdout_logfile=/var/log/trino-stdout.log
stderr_logfile=/var/log/trino-stderr.log

[program:flask]
command=/app/venv/bin/gunicorn -b 0.0.0.0:3000 -w 2 --chdir /app/backend app:app
directory=/app/backend
autostart=true
autorestart=true
environment=CONFIG_PATH="%(ENV_CONFIG_PATH)s"
stdout_logfile=/var/log/flask-stdout.log
stderr_logfile=/var/log/flask-stderr.log
